{{define "makefile"}}
run:
	go run cmd/meetspace/main.go
	
swagger:
    swag init -o ./docs -d ./cmd/todo
	swag init -g ./cmd/meetspace/main.go -o ./docs

run-test:
    GIN_MODE=test go test -v -cover -coverprofile=coverage.out ./....

# Project variables
BINARY_NAME=myapp
PKG=./...

# Go commands
GO=go
GOFMT=gofmt

# Default command to run if no other target is provided
all: build

# Build the binary
build:
	$(GO) build -o $(BINARY_NAME)

# Run the application
run: build
	./$(BINARY_NAME)

# Test the code
test:
	$(GO) test -v $(PKG)

# Format the code
fmt:
	$(GOFMT) -s -w .

# Lint the code (optional)
lint:
	golangci-lint run

# Clean up build files
clean:
	rm -f $(BINARY_NAME)

# Tidy dependencies
tidy:
	$(GO) mod tidy

# Install necessary Go tools
tools:
	go install github.com/golangci/golangci-lint/cmd/golangci-lint@latest

# Run all the tests and check formatting
ci: fmt test lint

.PHONY: all build run test fmt lint clean tidy tools ci


{{end}}
